apiVersion: v1
kind: Service
metadata:
  name: jasmin-dlr-service
  labels:
    app: jasmin-dlr
spec:
  type: NodePort  # Use NodePort for external access
  selector:
    app: jasmin-dlr
  ports:
    - protocol: TCP
      port: 80          # Exposed service port
      targetPort: 5000   # Flask container port
      nodePort: 30080   # Optional: Specify a NodePort (default range is 30000-32767)
---
apiVersion: v1
kind: Pod
metadata:
  name: jasmin-dlr-pod
  labels:
    app: jasmin-dlr
spec:
  containers:
    - name: jasmin-dlr-container
      image: jasmin-dlr-image:latest  # Replace with the correct image name
      ports:
        - containerPort: 5000   # Flask is running on this port
      env:
        - name: FLASK_ENV
          value: "production"  # Set Flask environment to production
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      volumeMounts:
        - name: log-volume
          mountPath: /app/logs  # Mount log volume
      livenessProbe:
        httpGet:
          path: /health  # Add a health check endpoint in your Flask app
          port: 5000
        initialDelaySeconds: 10
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /ready  # Add a readiness check endpoint in your Flask app
          port: 5000
        initialDelaySeconds: 5
        periodSeconds: 5
  volumes:
    - name: log-volume
      emptyDir: {}             # You can change this to a persistent volume
